[package]
name = "pulsecast-operator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anchor-client = "=1.0.2"
anchor-lang = "=1.0.2"
anyhow = "=1.0.100"
clap = { version = "=4.5.48", features = ["derive"] }
pulsecast = { path = "../../programs/pulsecast", features = ["no-entrypoint"] }
solana-keypair = "=3.1.2"
solana-system-interface = "=3.3.0"
